#!/usr/bin/env python3
"""
Car Report Generator - Create Word and PDF reports with car information and images.

This script allows users to:
1. Browse existing detailed car info txt files (from car_info_lookup.py)
2. Select one to use as the content source
3. Choose an image to include in the report
4. Generate a professionally formatted Word document (.docx)
5. Convert and save the same content as a PDF file

Usage:
    python3 car_report_generator.py                           # Interactive mode
    python3 car_report_generator.py --txt-file report.txt     # Specify txt file directly
    python3 car_report_generator.py --image photo.jpg         # Specify image directly
    python3 car_report_generator.py --txt-file r.txt --image p.jpg  # Both specified

Libraries used:
    - python-docx for Word document generation
    - reportlab for PDF generation
"""

import argparse
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Optional

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from reportlab.lib.colors import HexColor
from PIL import Image as PILImage


def list_txt_files(directory: Path) -> list[Path]:
    """List all txt files in a directory (focusing on detailed_* files)."""
    files = sorted([
        f for f in directory.iterdir()
        if f.is_file() and f.suffix.lower() == ".txt" and f.name.startswith("detailed_")
    ])
    return files


def list_images(directory: Path) -> list[Path]:
    """List all image files in a directory."""
    extensions = {".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"}
    images = sorted([
        f for f in directory.iterdir()
        if f.is_file() and f.suffix.lower() in extensions
    ])
    return images


def parse_detailed_txt(file_path: Path) -> dict:
    """
    Parse a detailed car info txt file to extract key information.
    Returns classification, description, matching vehicles, etc.
    """
    content = file_path.read_text(encoding="utf-8")

    result = {
        "file_path": str(file_path),
        "file_name": file_path.name,
        "classification": None,
        "confidence": None,
        "description": None,
        "matching_vehicles": [],
        "image_name": None,
        "raw_content": content,
    }

    # Extract classification
    class_match = re.search(r"Classification:\s*([^\n]+)", content)
    if class_match:
        result["classification"] = class_match.group(1).strip()

    # Extract confidence
    conf_match = re.search(r"Confidence:\s*([^\n]+)", content)
    if conf_match:
        result["confidence"] = conf_match.group(1).strip()

    # Extract original image name
    img_match = re.search(r"Original image:\s*([^\n]+)", content)
    if img_match:
        result["image_name"] = img_match.group(1).strip()

    # Extract the detailed description from TinyLlama section
    desc_match = re.search(
        r"DETAILED DESCRIPTION \(Generated by TinyLlama\)\s*-+\s*(.*?)(?=\n={10,}|\Z)",
        content,
        re.DOTALL | re.IGNORECASE
    )
    if desc_match:
        result["description"] = desc_match.group(1).strip()

    # Extract matching vehicles
    vehicles_section = re.search(
        r"MATCHING VEHICLES FROM DATABASE\s*-+\s*(.*?)(?=\n-{10,}|\nDETAILED DESCRIPTION)",
        content,
        re.DOTALL | re.IGNORECASE
    )
    if vehicles_section:
        vehicle_text = vehicles_section.group(1)
        # Parse each vehicle entry
        vehicle_pattern = r"•\s*([^\n]+)\s*\n\s*Engine:\s*([^\n]+)\s*\n\s*Power:\s*([^\n]+)\s*\n\s*Fuel:\s*([^\n]+)"
        for match in re.finditer(vehicle_pattern, vehicle_text):
            result["matching_vehicles"].append({
                "name": match.group(1).strip(),
                "engine": match.group(2).strip(),
                "power": match.group(3).strip(),
                "fuel": match.group(4).strip(),
            })

    return result


class CarReportGenerator:
    """Generates Word and PDF reports for car information."""

    def __init__(self):
        pass

    def create_word_document(
        self,
        output_path: Path,
        car_name: str,
        image_path: Optional[Path],
        description: str,
        matching_vehicles: list[dict]
    ) -> None:
        """Create a Word document with car information."""
        doc = Document()

        # Set up styles
        title_style = doc.styles['Title']
        title_style.font.size = Pt(24)
        title_style.font.bold = True

        heading_style = doc.styles['Heading 1']
        heading_style.font.size = Pt(16)

        normal_style = doc.styles['Normal']
        normal_style.font.size = Pt(11)

        # Title: Car Name
        title = doc.add_paragraph()
        title_run = title.add_run(car_name.upper())
        title_run.font.size = Pt(28)
        title_run.font.bold = True
        title_run.font.color.rgb = RGBColor(0, 51, 102)  # Dark blue
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()  # Spacer

        # Image section
        if image_path and image_path.exists():
            try:
                # Add image centered
                img_para = doc.add_paragraph()
                img_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
                run = img_para.add_run()
                
                # Resize image to fit within page margins (max 6 inches wide)
                with PILImage.open(image_path) as img:
                    width, height = img.size
                    max_width = 6 * 72  # 6 inches in points
                    if width > max_width:
                        ratio = max_width / width
                        width = max_width
                        height = height * ratio
                
                run.add_picture(str(image_path), width=Inches(6))
                doc.add_paragraph()  # Spacer
            except Exception as e:
                doc.add_paragraph(f"[Image could not be loaded: {e}]")

        # Detailed Information heading
        doc.add_paragraph("DETAILED INFORMATION", style='Heading 1')
        doc.add_paragraph()

        # Description
        if description:
            desc_para = doc.add_paragraph(description)
            desc_para.style = normal_style
        else:
            doc.add_paragraph("No detailed description available.")

        doc.add_paragraph()  # Spacer

        # Matching Vehicles section
        if matching_vehicles:
            doc.add_paragraph("MATCHING VEHICLES FROM CATALOG", style='Heading 1')
            doc.add_paragraph()

            for vehicle in matching_vehicles:
                vehicle_para = doc.add_paragraph()
                vehicle_para.add_run(f"• {vehicle['name']}").bold = True
                vehicle_para.add_run(f"\n    Engine: {vehicle['engine']}")
                vehicle_para.add_run(f"\n    Power:  {vehicle['power']}")
                vehicle_para.add_run(f"\n    Fuel:   {vehicle['fuel']}")
                doc.add_paragraph()  # Small spacer

        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph()
        footer_run = footer.add_run(f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Car Finder Report")
        footer_run.font.size = Pt(9)
        footer_run.font.italic = True
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Save the document
        doc.save(str(output_path))
        print(f"✓ Word document saved: {output_path}")

    def create_pdf_document(
        self,
        output_path: Path,
        car_name: str,
        image_path: Optional[Path],
        description: str,
        matching_vehicles: list[dict]
    ) -> None:
        """Create a PDF document with car information using reportlab."""
        
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=20,
            alignment=1,  # Center
            textColor=HexColor('#003366'),
            fontName='Helvetica-Bold'
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            spaceBefore=15,
            spaceAfter=10,
            textColor=HexColor('#003366'),
            fontName='Helvetica-Bold'
        )
        
        normal_style = ParagraphStyle(
            'CustomNormal',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            spaceAfter=8
        )
        
        vehicle_style = ParagraphStyle(
            'VehicleStyle',
            parent=styles['Normal'],
            fontSize=10,
            leading=13,
            leftIndent=20
        )

        story = []

        # Title
        story.append(Paragraph(car_name.upper(), title_style))
        story.append(Spacer(1, 20))

        # Image
        if image_path and image_path.exists():
            try:
                # Calculate image dimensions (max 5.5 inches wide)
                with PILImage.open(image_path) as img:
                    width, height = img.size
                    max_width = 5.5 * inch
                    if width > max_width:
                        ratio = max_width / width
                        width = max_width
                        height = height * ratio
                
                img = RLImage(str(image_path), width=width, height=height)
                story.append(img)
                story.append(Spacer(1, 20))
            except Exception as e:
                story.append(Paragraph(f"[Image could not be loaded: {e}]", normal_style))

        # Detailed Information
        story.append(Paragraph("DETAILED INFORMATION", heading_style))
        story.append(Spacer(1, 8))
        
        if description:
            # Split description into paragraphs
            paragraphs = description.split('\n\n')
            for para in paragraphs:
                if para.strip():
                    story.append(Paragraph(para.strip(), normal_style))
        else:
            story.append(Paragraph("No detailed description available.", normal_style))

        story.append(Spacer(1, 15))

        # Matching Vehicles
        if matching_vehicles:
            story.append(Paragraph("MATCHING VEHICLES FROM CATALOG", heading_style))
            story.append(Spacer(1, 8))
            
            for vehicle in matching_vehicles:
                vehicle_text = (
                    f"<b>• {vehicle['name']}</b><br/>"
                    f"    Engine: {vehicle['engine']}<br/>"
                    f"    Power:  {vehicle['power']}<br/>"
                    f"    Fuel:   {vehicle['fuel']}"
                )
                story.append(Paragraph(vehicle_text, vehicle_style))
                story.append(Spacer(1, 8))

        # Footer
        story.append(Spacer(1, 30))
        footer_text = f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Car Finder Report"
        story.append(Paragraph(footer_text, ParagraphStyle(
            'Footer',
            fontSize=9,
            alignment=1,
            textColor=HexColor('#666666'),
            fontName='Helvetica-Oblique'
        )))

        # Build the PDF
        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch
        )
        doc.build(story)
        print(f"✓ PDF document saved: {output_path}")


def interactive_mode(txt_dir: Path, image_dir: Path, output_dir: Path) -> None:
    """Run the interactive workflow for generating reports."""
    generator = CarReportGenerator()

    while True:
        # List detailed txt files
        txt_files = list_txt_files(txt_dir)

        if not txt_files:
            print(f"\nNo detailed txt files found in: {txt_dir}")
            print("Run car_info_lookup.py first to generate some detailed reports.")
            return

        print(f"\nDetailed car info reports found in: {txt_dir}")
        print("-" * 50)
        for i, f in enumerate(txt_files, 1):
            print(f"  [{i}] {f.name}")
        print("-" * 50)
        print("  [Q] Quit")
        print()

        choice = input("Select a report by number (or Q to quit): ").strip()

        if choice.lower() in ("q", "quit", "exit"):
            print("Goodbye!")
            return

        if not choice.isdigit():
            print("Please enter a valid number or Q to quit.")
            continue

        idx = int(choice)
        if idx < 1 or idx > len(txt_files):
            print(f"Please enter a number between 1 and {len(txt_files)}.")
            continue

        selected_txt = txt_files[idx - 1]
        print(f"\nReading: {selected_txt.name}...")
        parsed = parse_detailed_txt(selected_txt)

        car_name = parsed.get("classification", "Unknown Car")
        print(f"Car type: {car_name}")
        print()

        # List images
        images = list_images(image_dir)

        if not images:
            print(f"No images found in: {image_dir}")
            print("Please add some images to this folder.")
            continue

        print(f"Images found in: {image_dir}")
        print("-" * 50)
        for i, img in enumerate(images, 1):
            print(f"  [{i}] {img.name}")
        print("-" * 50)
        print()

        img_choice = input("Select an image by number: ").strip()

        if not img_choice.isdigit():
            print("Please enter a valid number.")
            continue

        img_idx = int(img_choice)
        if img_idx < 1 or img_idx > len(images):
            print(f"Please enter a number between 1 and {len(images)}.")
            continue

        selected_image = images[img_idx - 1]
        print(f"Selected image: {selected_image.name}")
        print()

        # Generate output filenames
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = re.sub(r'[^\w\-]', '_', car_name.lower())
        
        word_path = output_dir / f"{safe_name}_report_{timestamp}.docx"
        pdf_path = output_dir / f"{safe_name}_report_{timestamp}.pdf"

        # Create the reports
        print("Generating reports...")
        try:
            generator.create_word_document(
                word_path,
                car_name,
                selected_image,
                parsed.get("description", ""),
                parsed.get("matching_vehicles", [])
            )
            generator.create_pdf_document(
                pdf_path,
                car_name,
                selected_image,
                parsed.get("description", ""),
                parsed.get("matching_vehicles", [])
            )
            print(f"\n✓ Reports saved to: {output_dir}")
        except Exception as e:
            print(f"\nError generating reports: {e}", file=sys.stderr)
            import traceback
            traceback.print_exc()

        print()
        again = input("Generate another report? (y/n): ").strip().lower()
        if again not in ("y", "yes"):
            print("Goodbye!")
            return


def main():
    parser = argparse.ArgumentParser(
        description="Car Report Generator - Create Word and PDF reports with car information and images",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
This tool reads detailed car info reports (from car_info_lookup.py) and generates
professionally formatted Word and PDF documents that include the car name, an image,
and the detailed description.

Examples:
  python3 car_report_generator.py                                    # Interactive mode
  python3 car_report_generator.py --txt-file detailed_bw.txt         # Specify txt file
  python3 car_report_generator.py --image photo.jpg                  # Specify image
  python3 car_report_generator.py --txt-file r.txt --image p.jpg     # Both specified
        """
    )
    parser.add_argument(
        "--txt-file", "-t",
        type=Path,
        help="Path to the detailed car info txt file"
    )
    parser.add_argument(
        "--image", "-i",
        type=Path,
        help="Path to the image to include in the report"
    )
    parser.add_argument(
        "--txt-dir",
        type=Path,
        default=Path(__file__).parent / "analysis_output",
        help="Directory containing detailed txt files (default: ./analysis_output/)"
    )
    parser.add_argument(
        "--image-dir",
        type=Path,
        default=Path(__file__).parent / "sample_images",
        help="Directory containing images (default: ./sample_images/)"
    )
    parser.add_argument(
        "--output-dir", "-o",
        type=Path,
        default=Path(__file__).parent / "reports",
        help="Directory to save generated reports (default: ./reports/)"
    )
    args = parser.parse_args()

    # Ensure output directory exists
    args.output_dir.mkdir(exist_ok=True)

    # If both txt and image are specified, run non-interactively
    if args.txt_file and args.image:
        generator = CarReportGenerator()
        parsed = parse_detailed_txt(args.txt_file)
        
        car_name = parsed.get("classification", "Unknown Car")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_name = re.sub(r'[^\w\-]', '_', car_name.lower())
        
        word_path = args.output_dir / f"{safe_name}_report_{timestamp}.docx"
        pdf_path = args.output_dir / f"{safe_name}_report_{timestamp}.pdf"

        print(f"Generating reports for: {car_name}")
        generator.create_word_document(
            word_path, car_name, args.image,
            parsed.get("description", ""),
            parsed.get("matching_vehicles", [])
        )
        generator.create_pdf_document(
            pdf_path, car_name, args.image,
            parsed.get("description", ""),
            parsed.get("matching_vehicles", [])
        )
        print(f"\n✓ Reports saved to: {args.output_dir}")
    else:
        # Interactive mode
        interactive_mode(args.txt_dir, args.image_dir, args.output_dir)


if __name__ == "__main__":
    main()
